-- Add signup_index to profiles table to track user signup order
-- This allows us to automatically award the "Early Adopter" badge

-- Add the column
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS signup_index BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Populate existing users based on created_at
-- We use a temporary CTE to calculate the rank for existing users
WITH ranked_profiles AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) as rank
    FROM public.profiles
)
UPDATE public.profiles p
SET signup_index = rp.rank
FROM ranked_profiles rp
WHERE p.id = rp.id;

-- Ensure future signups get the next available index
-- If there are already users, we need to restart the sequence at the next value
SELECT setval(
    pg_get_serial_sequence('public.profiles', 'signup_index'), 
    COALESCE((SELECT MAX(signup_index) FROM public.profiles), 0) + 1, 
    false
);

-- Note: The signup_index is automatically assigned on INSERT
-- because of the GENERATED BY DEFAULT AS IDENTITY clause.
